services:
  - type: web
    name: ajo-backend
    env: docker
    repo: https://github.com/athallahrafi18/project-ajo
    region: oregon
    branch: main
    rootDir: ajo-backend
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: tramway.proxy.rlwy.net
      - key: DB_PORT
        value: 26128
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        sync: false   # kamu bisa isi nanti di dashboard Render
